<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;


/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function findListProducts($categoryURL = null)
    {
        $result = $this->createQueryBuilder('p')
            ->leftJoin('p.category','c')
            ->where('p.enabled = :enabled')
            ->andWhere('p.price > :price')
            ->setParameters(['enabled' => true, 'price' => 0])
            ->getQuery();
        return $result;
    }

    public function findAll()
    {
        $result = $this->createQueryBuilder('p')
            ->where('p.enabled = :enabled')
            ->andWhere('p.price > :price')
            ->setParameters(['enabled' => true, 'price' => 0])
            ->getQuery()->getResult();
        return $result;
    }

    public function findAllBrans()
    {
        $result = $this->createQueryBuilder('p')
            ->groupBy('p.brand')
            ->orderBy('p.brand', 'ASC')
            ->getQuery()->getResult();
        return $result;
    }


}
