<?php

namespace AppBundle\Repository;

/**
 * ProductGaleryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductGaleryRepository extends \Doctrine\ORM\EntityRepository
{
}
